/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.NhanvienDAO;
import MODEL.NhanVien;
import helper.DialogHelper;
import helper.ShareHelper;

/**
 *
 * @author ADMIN
 */
public class DangNhapJDialog extends java.awt.Dialog {
    NhanvienDAO dao = new NhanvienDAO();
    void init(){
        setLocationRelativeTo(null);
        
        txtmanv.setText("nv01");
        txtmatkhau.setText("123");
    }
    void login(){
        
        String manv = txtmanv.getText();
       String matkhau = new String(txtmatkhau.getPassword());
        
        try {
            NhanVien nhanvien = dao.findByld(manv);
            if(nhanvien != null){
                String matkhau2 = nhanvien.getMatkhau();
            if (matkhau.equals(matkhau2)) {
                ShareHelper.USER = nhanvien;
                DialogHelper.alert(this, "Đăng nhập thành công !");
                this.dispose();
            }else{
                DialogHelper.alert(this, "Sai mật khẩu");
            }
            }else{
                DialogHelper.alert(this, "Sai tên đăng nhập");
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu !");
        }
    }
    void exit(){
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không ?")) {
            System.exit(0);
        }
    }
    /**
     * Creates new form DangNhapJDialog
     */
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndangnhap = new javax.swing.JButton();
        txtmanv = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblmatkhau = new javax.swing.JLabel();
        lbtitle = new javax.swing.JLabel();
        btndangnhap1 = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        txtmatkhau = new javax.swing.JPasswordField();

        btndangnhap.setText("Đăng nhập");

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/security.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblmatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmatkhau.setText("Mật khẩu");

        lbtitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbtitle.setForeground(new java.awt.Color(0, 153, 0));
        lbtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitle.setText("ĐẰNG NHẬP");
        lbtitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btndangnhap1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndangnhap1.setText("Đăng nhập");
        btndangnhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhap1ActionPerformed(evt);
            }
        });

        btnketthuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnketthuc.setText("Kết thúc");
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimage)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblmatkhau)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btndangnhap1)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnketthuc)))
                                        .addGap(53, 53, 53))
                                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(lblmatkhau)
                        .addGap(18, 18, 18)
                        .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndangnhap1)
                            .addComponent(btnketthuc))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btndangnhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhap1ActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btndangnhap1ActionPerformed

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btnketthucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDialog dialog = new DangNhapJDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangnhap;
    private javax.swing.JButton btndangnhap1;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblmatkhau;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JPasswordField txtmatkhau;
    // End of variables declaration//GEN-END:variables
}
