/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.HocVienDAO;
import DAO.NguoiHocDAO;
import MODEL.HocVien;
import MODEL.NguoiHoc;
import helper.DialogHelper;
import helper.ShareHelper;
import helper.jdbcHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class HocVienJFrame extends javax.swing.JFrame {

    public Integer MaKH;
    HocVienDAO dao = new HocVienDAO();
    NguoiHocDAO nhdao = new NguoiHocDAO();

    /**
     * Creates new form HocVienJFrame
     * @param MaKH
     */
    public HocVienJFrame(Integer MaKH) {
        initComponents();
        init();
        this.MaKH = MaKH;
        
        
    }
   void init(){
       setIconImage(ShareHelper.APP_ICON);
       this.setLocationRelativeTo(null);
   }
    HocVienJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillComboBox();
        this.fillGridview();
    }

    void fillComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbonguoihoc.getModel();
//         model.removeAllElements();
        try {
            List<NguoiHoc> list = nhdao.selectByCourse(MaKH);
            for (NguoiHoc nh : list) {
                model.addElement(nh);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn học viên!");
        }
    }

    void fillGridview() {
        DefaultTableModel model = (DefaultTableModel) tblgridview.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT hv.*, nh.HoTen FROM HocVien hv "
                    + " JOIN NguoiHoc nh ON nh.MaNH = hv.MaNH WHERE MaKH=?";
            ResultSet rs = jdbcHelper.executeQuery(sql, MaKH);
            while (rs.next()) {
                double diem = rs.getDouble("Diem");
                Object[] row = {
                    rs.getInt("MaHV"),
                    rs.getString("MaNH"),
                    rs.getString("HoTen"),
                    diem, false
                };
                if (rdotatca.isSelected()) {
                    model.addRow(row);
                } else if (rdodannhapdiem.isSelected() && diem >= 0) {
                    model.addRow(row);

                } else if (rdochuanhapdiem.isSelected() && diem < 0) {
                    model.addRow(row);
                }
            }

        } catch (SQLException e) {
            DialogHelper.alert(this, "Lỗi truy vấn học viên!");
            System.out.println(e.toString());
        }
    }

    void insert() {
        NguoiHoc nguoiHoc = (NguoiHoc) cbonguoihoc.getSelectedItem();

        HocVien model = new HocVien();
        model.setMaKH(MaKH);
        model.setMaNH(nguoiHoc.getMaNH());
        model.setDiem(Double.valueOf(txtdiem.getText()));

        try {
            dao.insert(model);
            this.fillComboBox();
            this.fillGridview();
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi thêm học viên vào khóa học!");
        }
    }

    void update() {
        for (int i = 0; i < tblgridview.getRowCount(); i++) {
            Integer mahv = (Integer) tblgridview.getValueAt(i, 0);
            String manh = (String) tblgridview.getValueAt(i, 1);
            Double diem = (Double) tblgridview.getValueAt(i, 3);
            Boolean isDelete = (Boolean) tblgridview.getValueAt(i, 4);

            if (isDelete) {
                dao.delete(mahv);
            } else {
                HocVien model = new HocVien();
                model.setMaHV(mahv);
                model.setMaKH(MaKH);
                model.setMaNH(manh);
                model.setDiem(diem);

                dao.update(model);
            }
        }
        this.fillComboBox();
        this.fillGridview();
        DialogHelper.alert(this, "cập nhật thành công!");
    }
//    public boolean check(){
//        if (txtd) {
//            
//        }
//        return true;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlhocvienkhac = new javax.swing.JPanel();
        cbonguoihoc = new javax.swing.JComboBox<>();
        txtdiem = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        pnlhvkh = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgridview = new javax.swing.JTable();
        rdotatca = new javax.swing.JRadioButton();
        rdodannhapdiem = new javax.swing.JRadioButton();
        rdochuanhapdiem = new javax.swing.JRadioButton();
        btncapnhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ HỌC VIÊN CỦA KHÓA HỌC");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlhocvienkhac.setBorder(javax.swing.BorderFactory.createTitledBorder("HỌC VIÊN KHÁC"));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlhocvienkhacLayout = new javax.swing.GroupLayout(pnlhocvienkhac);
        pnlhocvienkhac.setLayout(pnlhocvienkhacLayout);
        pnlhocvienkhacLayout.setHorizontalGroup(
            pnlhocvienkhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhocvienkhacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbonguoihoc, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnthem)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        pnlhocvienkhacLayout.setVerticalGroup(
            pnlhocvienkhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhocvienkhacLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlhocvienkhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbonguoihoc)
                    .addComponent(txtdiem)
                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlhvkh.setBorder(javax.swing.BorderFactory.createTitledBorder("HỌC VIÊN CỦA KHÓA HỌC"));

        tblgridview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HV", "Mã NH", "Họ và tên", "Điểm", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblgridview);

        buttonGroup1.add(rdotatca);
        rdotatca.setSelected(true);
        rdotatca.setText("Tất cả");
        rdotatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdotatcaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdodannhapdiem);
        rdodannhapdiem.setText("Đã nhập điểm");
        rdodannhapdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodannhapdiemActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdochuanhapdiem);
        rdochuanhapdiem.setText("Chưa nhập điểm");
        rdochuanhapdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdochuanhapdiemActionPerformed(evt);
            }
        });

        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlhvkhLayout = new javax.swing.GroupLayout(pnlhvkh);
        pnlhvkh.setLayout(pnlhvkhLayout);
        pnlhvkhLayout.setHorizontalGroup(
            pnlhvkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhvkhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlhvkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhvkhLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(pnlhvkhLayout.createSequentialGroup()
                        .addComponent(rdotatca)
                        .addGap(18, 18, 18)
                        .addComponent(rdodannhapdiem)
                        .addGap(18, 18, 18)
                        .addComponent(rdochuanhapdiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncapnhat)
                        .addGap(21, 21, 21))))
        );
        pnlhvkhLayout.setVerticalGroup(
            pnlhvkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhvkhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlhvkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdotatca)
                    .addComponent(rdodannhapdiem)
                    .addComponent(rdochuanhapdiem)
                    .addComponent(btncapnhat))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlhvkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlhocvienkhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlhocvienkhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlhvkh, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void rdotatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdotatcaActionPerformed
        // TODO add your handling code here:
        fillGridview();
    }//GEN-LAST:event_rdotatcaActionPerformed

    private void rdodannhapdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodannhapdiemActionPerformed
        // TODO add your handling code here:
        fillGridview();
    }//GEN-LAST:event_rdodannhapdiemActionPerformed

    private void rdochuanhapdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdochuanhapdiemActionPerformed
        // TODO add your handling code here:
        fillGridview();
    }//GEN-LAST:event_rdochuanhapdiemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.fillComboBox();
        this.fillGridview();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HocVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonguoihoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlhocvienkhac;
    private javax.swing.JPanel pnlhvkh;
    private javax.swing.JRadioButton rdochuanhapdiem;
    private javax.swing.JRadioButton rdodannhapdiem;
    private javax.swing.JRadioButton rdotatca;
    private javax.swing.JTable tblgridview;
    private javax.swing.JTextField txtdiem;
    // End of variables declaration//GEN-END:variables
}
