/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import helper.DialogHelper;
import helper.ShareHelper;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lbldongho.setText(format.format(new Date()));
            }
        }).start();
        this.openWelcome();
        this.openLogin();

    }
    //đăng nhập

    void openLogin() {
        new DangNhapJDialog(this, true).setVisible(true);
    }

    void openWelcome() {
        new ChaoJDialog(this, true).setVisible(true);
    }
    //kết thúc

    void Exit() {
        if (DialogHelper.confirm(this, "bạn thật sự muốn kết thúc ?")) {
            System.exit(0);
        }
    }
    //đăng xuất

    void Logoff() {
        ShareHelper.logoff();
        this.openLogin();
    }
    // chuyên đề

    void openChuyenDe() {
        if (ShareHelper.authenticated()) {
            new ChuyenDeJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    // người học

    void openNguoiHoc() {
        if (ShareHelper.authenticated()) {
            new NguoihocJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    // học viên

    void openHocVien() {
        if (ShareHelper.authenticated()) {
            new HocVienJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    // khoá học

    void openKhoaHoc() {
        if (ShareHelper.authenticated()) {
            new KhoaHocJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    //nhân viên

    void openNhanVien() {
        if (ShareHelper.authenticated()) {
            new NhanVienJFrame().setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
    // thống kê người học từng năm

    void openThongKe(int index) {
        if (ShareHelper.authenticated()) {
            new ThongKeJFrame(index).setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openAbout() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }
    // gioi thiệu

//    void openWebsite(){
//        try {
//            Desktop.getDesktop().browse(new File("PolyPro/UI/index").toURI());
//        } catch (IOException e) {
//            DialogHelper.alert(this, "Không tìm thấy file hướng dẫn!");
//        }
//    }
    void openWebsite() throws URISyntaxException, IOException {
        Desktop.getDesktop().browse(getClass().getResource("/helper/index.html").toURI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jButton6 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        pnltrangthai = new javax.swing.JPanel();
        lbltrangthai = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        lblnoidung = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btndangxuat = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        btnchuyende = new javax.swing.JButton();
        btnnguoihoc = new javax.swing.JButton();
        btnkhoahoc = new javax.swing.JButton();
        btnhuongdan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuhethong = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnidoimatkhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniketthuc = new javax.swing.JMenuItem();
        mnuquanly = new javax.swing.JMenu();
        mniqlnguoihoc = new javax.swing.JMenuItem();
        mniqlchuyende = new javax.swing.JMenuItem();
        mniqlkhoahoc = new javax.swing.JMenuItem();
        mniqlnhanvien = new javax.swing.JMenuItem();
        mnuthongke = new javax.swing.JMenu();
        mnitknguoihoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnitkbangdiem = new javax.swing.JMenuItem();
        mnitkkhoahoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnitkdoanhthu = new javax.swing.JMenuItem();
        mnutrogiup = new javax.swing.JMenu();
        mnigioithieu = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniwebsite = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnltrangthai.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltrangthai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Button-Info-icon.png"))); // NOI18N
        lbltrangthai.setText("Hệ quản lý đào tạo");

        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Alarm-clock-icon.png"))); // NOI18N
        lbldongho.setText("10:55");

        javax.swing.GroupLayout pnltrangthaiLayout = new javax.swing.GroupLayout(pnltrangthai);
        pnltrangthai.setLayout(pnltrangthaiLayout);
        pnltrangthaiLayout.setHorizontalGroup(
            pnltrangthaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltrangthaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltrangthai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldongho)
                .addGap(19, 19, 19))
        );
        pnltrangthaiLayout.setVerticalGroup(
            pnltrangthaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltrangthaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnltrangthaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltrangthai)
                    .addComponent(lbldongho))
                .addContainerGap())
        );

        lblnoidung.setBackground(new java.awt.Color(255, 255, 255));
        lblnoidung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnoidung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo.png"))); // NOI18N
        lblnoidung.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblnoidung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblnoidung.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jToolBar1.setRollover(true);

        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Log-Out-icon.png"))); // NOI18N
        btndangxuat.setText("Đăng xuất");
        btndangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btndangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndangxuat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btndangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btndangxuat);

        btnketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Stop.png"))); // NOI18N
        btnketthuc.setText("Kết thúc");
        btnketthuc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnketthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnketthuc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnketthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnketthuc);

        btnchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Actions-view-list-details-icon.png"))); // NOI18N
        btnchuyende.setText("Chuyên đề");
        btnchuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnchuyende.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnchuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnchuyende);

        btnnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Social-network-icon.png"))); // NOI18N
        btnnguoihoc.setText("Người học");
        btnnguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnguoihoc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnnguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnguoihoc);

        btnkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ssl-certificates-icon.png"))); // NOI18N
        btnkhoahoc.setText("Khóa học");
        btnkhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhoahoc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnkhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkhoahoc);

        btnhuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/World-icon.png"))); // NOI18N
        btnhuongdan.setText("Hướng dẫn");
        btnhuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhuongdan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnhuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuongdanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhuongdan);

        mnuhethong.setBorder(null);
        mnuhethong.setText("Hệ thống");

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/key-icon.png"))); // NOI18N
        mnidangnhap.setText("Đăng nhập");
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidangnhap);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Log-Out-icon.png"))); // NOI18N
        mnidangxuat.setText("Đăng xuất");
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidangxuat);
        mnuhethong.add(jSeparator1);

        mnidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Button-Refresh-icon.png"))); // NOI18N
        mnidoimatkhau.setText("Đổi mật khẩu");
        mnidoimatkhau.setBorder(null);
        mnuhethong.add(mnidoimatkhau);
        mnuhethong.add(jSeparator2);

        mniketthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/stop-icon.png"))); // NOI18N
        mniketthuc.setText("Kết thúc");
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        mnuhethong.add(mniketthuc);

        jMenuBar1.add(mnuhethong);

        mnuquanly.setText("Quản lý");

        mniqlnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Social-network-icon.png"))); // NOI18N
        mniqlnguoihoc.setText("Người học");
        mniqlnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniqlnguoihocActionPerformed(evt);
            }
        });
        mnuquanly.add(mniqlnguoihoc);

        mniqlchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Actions-view-list-details-icon.png"))); // NOI18N
        mniqlchuyende.setText("Chuyên đề");
        mniqlchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniqlchuyendeActionPerformed(evt);
            }
        });
        mnuquanly.add(mniqlchuyende);

        mniqlkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ssl-certificates-icon.png"))); // NOI18N
        mniqlkhoahoc.setText("Khóa học");
        mniqlkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniqlkhoahocActionPerformed(evt);
            }
        });
        mnuquanly.add(mniqlkhoahoc);

        mniqlnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Groups-Rescuers-Light-icon.png"))); // NOI18N
        mniqlnhanvien.setText("Quản lý nhân viên");
        mniqlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniqlnhanvienActionPerformed(evt);
            }
        });
        mnuquanly.add(mniqlnhanvien);

        jMenuBar1.add(mnuquanly);

        mnuthongke.setText("Thống kê");

        mnitknguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Apps-preferences-contact-list-icon.png"))); // NOI18N
        mnitknguoihoc.setText("Người học từng năm");
        mnitknguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitknguoihocActionPerformed(evt);
            }
        });
        mnuthongke.add(mnitknguoihoc);
        mnuthongke.add(jSeparator3);

        mnitkbangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Actions-document-open-icon.png"))); // NOI18N
        mnitkbangdiem.setText("Bảng điểm khóa học");
        mnitkbangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitkbangdiemActionPerformed(evt);
            }
        });
        mnuthongke.add(mnitkbangdiem);

        mnitkkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/chart-bar-add-icon.png"))); // NOI18N
        mnitkkhoahoc.setText("Bảng điểm từng khóa hoc");
        mnitkkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitkkhoahocActionPerformed(evt);
            }
        });
        mnuthongke.add(mnitkkhoahoc);
        mnuthongke.add(jSeparator4);

        mnitkdoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Dollar-USD-icon.png"))); // NOI18N
        mnitkdoanhthu.setText("Danh thu từng chuyên đề");
        mnitkdoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitkdoanhthuActionPerformed(evt);
            }
        });
        mnuthongke.add(mnitkdoanhthu);

        jMenuBar1.add(mnuthongke);

        mnutrogiup.setText("Trợ giúp");

        mnigioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnigioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/World-icon.png"))); // NOI18N
        mnigioithieu.setText("Hướng dẫn sử dụng");
        mnigioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnigioithieuActionPerformed(evt);
            }
        });
        mnutrogiup.add(mnigioithieu);
        mnutrogiup.add(jSeparator5);

        mniwebsite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Home-icon.png"))); // NOI18N
        mniwebsite.setText("Giới thiệu sản phẩm");
        mniwebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniwebsiteActionPerformed(evt);
            }
        });
        mnutrogiup.add(mniwebsite);

        jMenuBar1.add(mnutrogiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnltrangthai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblnoidung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyendeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
    }//GEN-LAST:event_btnchuyendeActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        // TODO add your handling code here:
        Logoff();
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btnnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoihocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
    }//GEN-LAST:event_btnnguoihocActionPerformed

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        // TODO add your handling code here:
        Exit();
    }//GEN-LAST:event_btnketthucActionPerformed

    private void btnkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoahocActionPerformed
        // TODO add your handling code here:
        openKhoaHoc();
    }//GEN-LAST:event_btnkhoahocActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnhuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuongdanActionPerformed
        try {
            // TODO add your handling code here:
            openWebsite();
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnhuongdanActionPerformed

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
        // TODO add your handling code here:
        openLogin();
    }//GEN-LAST:event_mnidangnhapActionPerformed

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
        // TODO add your handling code here:
        Logoff();
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
        // TODO add your handling code here:
        Exit();
    }//GEN-LAST:event_mniketthucActionPerformed

    private void mniqlnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniqlnguoihocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
    }//GEN-LAST:event_mniqlnguoihocActionPerformed

    private void mniqlchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniqlchuyendeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
    }//GEN-LAST:event_mniqlchuyendeActionPerformed

    private void mniqlkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniqlkhoahocActionPerformed
        // TODO add your handling code here:
        openKhoaHoc();
    }//GEN-LAST:event_mniqlkhoahocActionPerformed

    private void mniqlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniqlnhanvienActionPerformed
        // TODO add your handling code here:
        openNhanVien();
    }//GEN-LAST:event_mniqlnhanvienActionPerformed

    private void mniwebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniwebsiteActionPerformed
        // TODO add your handling code here:
     openAbout();
    }//GEN-LAST:event_mniwebsiteActionPerformed

    private void mnigioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnigioithieuActionPerformed
        try {
            openWebsite();
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnigioithieuActionPerformed

    private void mnitknguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitknguoihocActionPerformed
        // TODO add your handling code here:
        try {
            openThongKe(0);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_mnitknguoihocActionPerformed

    private void mnitkbangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitkbangdiemActionPerformed
        // TODO add your handling code here:
       
        try {
             openThongKe(1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mnitkbangdiemActionPerformed

    private void mnitkkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitkkhoahocActionPerformed
        // TODO add your handling code here:
        try {
            
        openThongKe(2);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mnitkkhoahocActionPerformed

    private void mnitkdoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitkdoanhthuActionPerformed
        // TODO add your handling code here:
        try {
              openThongKe(3);  
        } catch (Exception e) {
        }
    
    }//GEN-LAST:event_mnitkdoanhthuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchuyende;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btnhuongdan;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JButton btnkhoahoc;
    private javax.swing.JButton btnnguoihoc;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JLabel lblnoidung;
    private javax.swing.JLabel lbltrangthai;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidoimatkhau;
    private javax.swing.JMenuItem mnigioithieu;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenuItem mniqlchuyende;
    private javax.swing.JMenuItem mniqlkhoahoc;
    private javax.swing.JMenuItem mniqlnguoihoc;
    private javax.swing.JMenuItem mniqlnhanvien;
    private javax.swing.JMenuItem mnitkbangdiem;
    private javax.swing.JMenuItem mnitkdoanhthu;
    private javax.swing.JMenuItem mnitkkhoahoc;
    private javax.swing.JMenuItem mnitknguoihoc;
    private javax.swing.JMenuItem mniwebsite;
    private javax.swing.JMenu mnuhethong;
    private javax.swing.JMenu mnuquanly;
    private javax.swing.JMenu mnuthongke;
    private javax.swing.JMenu mnutrogiup;
    private javax.swing.JPanel pnltrangthai;
    // End of variables declaration//GEN-END:variables
}
