/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.KhoaHocDAO;
import DAO.ThongKeDAO;
import MODEL.KhoaHoc;
import helper.ShareHelper;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ThongKeJFrame extends javax.swing.JFrame {
     ThongKeDAO dao = new ThongKeDAO();
     KhoaHocDAO khdao = new KhoaHocDAO();

    private ThongKeJFrame() {
    }

    
   
     void init(){
         setIconImage(ShareHelper.APP_ICON);
         setLocationRelativeTo(null);
     }
     void fillComboBoxKhoaHoc(){
         DefaultComboBoxModel model = (DefaultComboBoxModel) cbokhoahoc.getModel();
         model.removeAllElements();
         
         List<KhoaHoc> list = khdao.select();
         for (KhoaHoc kh : list) {
             model.addElement(kh);
         }
         cbokhoahoc.setSelectedIndex(0);
     }
     void fillComboBoxNam(){
         DefaultComboBoxModel model = (DefaultComboBoxModel) cbonam.getModel();
         model.removeAllElements();
         
         List<KhoaHoc> list = khdao.select();
         for (KhoaHoc kh : list) {
             int nam = kh.getNgayKG().getYear() +1900;
             if (model.getIndexOf(nam)<0) {
                 model.addElement(nam);
             }
         }
         cbonam.setSelectedIndex(0);
     }
     void  fillTableBangDiem(){
         DefaultTableModel model = (DefaultTableModel) tblbangdiem.getModel();
         model.setRowCount(0);
         
         KhoaHoc kh = (KhoaHoc) cbokhoahoc.getSelectedItem();
         List<Object[]> list = dao.getBangDiem(kh.getMaKH());
         for (Object[] row : list) {
             model.addRow(row);
         }
     }
     void fillTableNguoiHoc(){
         DefaultTableModel model = (DefaultTableModel) tblnguoihoc.getModel();
         model.setRowCount(0);
         
         List<Object[]> list = dao.getNguoiHoc();
         for (Object[] row : list) {
             model.addRow(row);
         }
     }
     void fillTableKhoaHoc(){
         DefaultTableModel model = (DefaultTableModel) tbltonghop.getModel();
         model.setRowCount(0);
         
         List<Object[]> list = dao.getDiemTheoChuyenDe();
         for (Object[] row : list) {
             model.addRow(row);
         }
     }
     void fillTableDoanhThu(){
         DefaultTableModel model = (DefaultTableModel) tbldanhthu.getModel();
         model.setRowCount(0);
         int nam = Integer.parseInt(cbonam.getSelectedItem().toString());
         List<Object[]> list = dao.getDoanhThu(nam);
         for (Object[] row : list) {
             model.addRow(row);
         }
                 
     }
     
    /**
     * Creates new form ThongKeJFrame
     * @param index
     */
    public ThongKeJFrame(int index) {
        initComponents();
        tabs.setSelectedIndex(index);
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnlnguoihoc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnguoihoc = new javax.swing.JTable();
        pnlbangdiem = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbangdiem = new javax.swing.JTable();
        lblkhoahoc = new javax.swing.JLabel();
        cbokhoahoc = new javax.swing.JComboBox<>();
        pnlkhoahoc = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltonghop = new javax.swing.JTable();
        pnldanhthu = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbldanhthu = new javax.swing.JTable();
        lblnam = new javax.swing.JLabel();
        cbonam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TỔNG HỢP - THỐNG KÊ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(0, 0, 153));
        lbltitle.setText("TỔNG HỢP - THỐNG KÊ");

        tblnguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NĂM", "SỐ NGƯỜI HỌC", "ĐẦU TIÊN", "SAU CÙNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblnguoihoc);

        javax.swing.GroupLayout pnlnguoihocLayout = new javax.swing.GroupLayout(pnlnguoihoc);
        pnlnguoihoc.setLayout(pnlnguoihocLayout);
        pnlnguoihocLayout.setHorizontalGroup(
            pnlnguoihocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnguoihocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlnguoihocLayout.setVerticalGroup(
            pnlnguoihocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnguoihocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(109, 109, 109))
        );

        tabs.addTab("NGƯỜI HỌC", pnlnguoihoc);

        tblbangdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ NH", "HỌ VÀ TÊN", "ĐIỂM", "XẾP LOẠI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblbangdiem);

        lblkhoahoc.setText("KHÓA HỌC");

        cbokhoahoc.setEditable(true);
        cbokhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbokhoahocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlbangdiemLayout = new javax.swing.GroupLayout(pnlbangdiem);
        pnlbangdiem.setLayout(pnlbangdiemLayout);
        pnlbangdiemLayout.setHorizontalGroup(
            pnlbangdiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbangdiemLayout.createSequentialGroup()
                .addGroup(pnlbangdiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlbangdiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
                    .addGroup(pnlbangdiemLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblkhoahoc)
                        .addGap(30, 30, 30)
                        .addComponent(cbokhoahoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        pnlbangdiemLayout.setVerticalGroup(
            pnlbangdiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbangdiemLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlbangdiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkhoahoc)
                    .addComponent(cbokhoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        tabs.addTab("BẢNG ĐIỂM", pnlbangdiem);

        tbltonghop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHUYÊN ĐỀ", "TỔNG HỢP HV", "CAO NHẤT", "THẤP NHẤT", "ĐIỂM TB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbltonghop);

        javax.swing.GroupLayout pnlkhoahocLayout = new javax.swing.GroupLayout(pnlkhoahoc);
        pnlkhoahoc.setLayout(pnlkhoahocLayout);
        pnlkhoahocLayout.setHorizontalGroup(
            pnlkhoahocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkhoahocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlkhoahocLayout.setVerticalGroup(
            pnlkhoahocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkhoahocLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        tabs.addTab("TỔNG HỢP ĐIỂM", pnlkhoahoc);

        tbldanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHUYÊN ĐỀ", "SỐ KHÓA", "SÔ HV", "DOANH THU", "HP CAO NHẤT", "HP THẤP NHẤT", "HP TRUNG BÌNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbldanhthu);

        lblnam.setText("NĂM");

        cbonam.setEditable(true);
        cbonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbonamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldanhthuLayout = new javax.swing.GroupLayout(pnldanhthu);
        pnldanhthu.setLayout(pnldanhthuLayout);
        pnldanhthuLayout.setHorizontalGroup(
            pnldanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldanhthuLayout.createSequentialGroup()
                .addGroup(pnldanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                    .addGroup(pnldanhthuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblnam)
                        .addGap(27, 27, 27)
                        .addComponent(cbonam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnldanhthuLayout.setVerticalGroup(
            pnldanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldanhthuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnldanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnam)
                    .addComponent(cbonam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        tabs.addTab("DANH THU", pnldanhthu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbokhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbokhoahocActionPerformed
        // TODO add your handling code here:
        fillTableBangDiem();
    }//GEN-LAST:event_cbokhoahocActionPerformed

    private void cbonamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbonamActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThu();
    }//GEN-LAST:event_cbonamActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.fillComboBoxKhoaHoc();
        this.fillTableNguoiHoc();
        this.fillTableBangDiem();
        this.fillTableKhoaHoc();
        this.fillComboBoxNam();
        this.fillTableDoanhThu();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbokhoahoc;
    private javax.swing.JComboBox<String> cbonam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblkhoahoc;
    private javax.swing.JLabel lblnam;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnlbangdiem;
    private javax.swing.JPanel pnldanhthu;
    private javax.swing.JPanel pnlkhoahoc;
    private javax.swing.JPanel pnlnguoihoc;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblbangdiem;
    private javax.swing.JTable tbldanhthu;
    private javax.swing.JTable tblnguoihoc;
    private javax.swing.JTable tbltonghop;
    // End of variables declaration//GEN-END:variables
}
